# Dockerfile.api

# Usa uma imagem base do Python
FROM python:3.9

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o código da API e o arquivo de dependências
COPY app.py db_utils.py requirements.txt ./

# Instala as dependências
RUN pip install -r requirements.txt

# Exponha a porta que o Flask usará
EXPOSE 8000

# Define o comando para iniciar o servidor Flask
CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]
